### ISSUE TITLE
Top level describe does not run when nested inside another describe

### ISSUE THREAD

**Issue by evanyeung** [facebookexperimental/reason-native#119]
In the following code, the inner describe block never runs and the test successfully passes
```
describe("Outer describe", ({test}) =>
  describe("Inner describe", ({test}) =>
    test("Inner test", ({expect}) =>
      expect.bool(true).toBe(false)
    )
  )
);
```

The test fails as expected if a local describe is used for the "Inner describe"
```
describe("Outer describe", ({test, describe}) =>
  describe("Inner describe", ({test}) =>
    test("Inner test", ({expect}) =>
      expect.bool(true).toBe(false)
    )
  )
);
```

Rather than failing silently, there should probably either be an indication that the inner describe block was skipped or nested top level describe blocks should be supported.

**Comment by bandersongit** [comment]
Thanks for filing @evanyeung, I think the thing to do is to cause the top level describe to throw an error if called inside a test, I think this change should be fairly straightforward

**Comment by bandersongit** [comment]
As of Rely 1.3.1 there is an error in this case. In the upcoming 2.0 release tests like this will be discovered and run.
