### ISSUE TITLE
Why are we throwing errors for parsers when things are not found?

### ISSUE THREAD

**Issue by kpsuperplane** [facebookexperimental/reason-native#12]
If you look at the definition of `build_InconsistentAssumptions` it simply throws an error when run.
https://github.com/facebookexperimental/reason-native/blob/4cd16aafd09c76ed7c81baf137b2691c61a6c32a/src/refmterr/lib/parseError.re#L444-L445

This is true for many parsers, including 
- `build_InconsistentAssumptions`
- `type_RecordFieldError`
- `type_FieldNotBelong`

https://github.com/facebookexperimental/reason-native/blob/4cd16aafd09c76ed7c81baf137b2691c61a6c32a/src/refmterr/lib/parseError.re#L516-L527

Would it not be simpler to simply return None on no match?

This is in direct contradiction with https://reasonml.github.io/docs/en/exception#tips-tricks, which says 
> When you have ordinary variants, you often don't need exceptions. For example, instead of throwing when item can't be found in a collection, try to return an option(item) (None in this case) instead.

**Comment by kpsuperplane** [comment]
Updated post as I realized this wasn't actually an error but rather a weird practice of returning `None`

**Comment by jordwalke** [comment]
Usually you don't want to throw exceptions to signify information. Save exceptions for things that are really failures of the app. The main exception is for perf critical code - which this is not.
