### ISSUE TITLE
Rely documentation links to missing file

### ISSUE THREAD

**Issue by michaelboulton** [facebookexperimental/reason-native#167]
https://reason-native.com/docs/rely/advanced#running-with-custom-reporters-https-githubcom-facebookexperimental-reason-native-blob-master-src-rely-reporterre links to https://github.com/facebookexperimental/reason-native/blob/master/src/rely/Reporter.re which doesn't exist - it should probably link to https://github.com/facebookexperimental/reason-native/tree/master/src/rely/reporters ?

**Comment by bandersongit** [comment]
Thanks for filing, I updated the link to https://github.com/facebookexperimental/reason-native/blob/master/src/rely/reporters/Reporter.re, it should be live shortly!
