### ISSUE TITLE
[Rely] Adding assertion count setup

### ISSUE THREAD

**Issue by WhoAteDaCake** [facebookexperimental/reason-native#180]
Using `expect.assertions` is extremely useful in jest. Is it possible to have similar functionality in rely?

**Comment by bandersongit** [comment]
Thanks for bringing this up! I've found myself writing some tests recently that could have used this functionality and I think it should be possible (if a little tricky) to add in.

**Comment by bandersongit** [comment]
expect.assertion matchers are included as of the latest release
