### ISSUE TITLE
Possible to publish preliminary NPM packages?

### ISSUE THREAD

**Issue by bryphe** [facebookexperimental/reason-native#22]
Since #16 is fixed - I would love to switch over some of my libraries to use this test runner (and be able to give more feedback).

However, one blocker is that I need to use `resolutions` in `esy` to get at the packages. This is a problem because the resolutions trickle through the dependency graph - for example, if I use `test-runner` in `revery`, any project that brings in `revery` as a dependency needs to __also specify these resolutions__. 

The motivation for this is I'd like to try it out on some of my core projects like https://github.com/bryphe/reason-gl-matrix that run both native tests and against JSOO - but if I add the `resolutions`, every project that depends on it would also need these resolutions.

Is it possible to publish preliminary NPM packages for this work?

**Comment by kyldvs** [comment]
Good point. I think we are finalizing a public name and are planning to publish it so that this is easy to consume on Monday.

Would specifying the resolutions be okay until that time?

**Comment by bryphe** [comment]
> Good point. I think we are finalizing a public name and are planning to publish it so that this is easy to consume on Monday.

Monday would be great! No rush.

**Comment by bandersongit** [comment]
It took a little longer than Monday, but test-runner has been renamed rely and is now published. https://www.npmjs.com/package/@reason-native/rely
