### ISSUE TITLE
Run tests for refmterr with Rely

### ISSUE THREAD

**Issue by kpsuperplane** [facebookexperimental/reason-native#25]
Have a fairly [basic PR](https://github.com/facebookexperimental/reason-native/pull/24) out for running tests for the subprojects with a bash script, but ideally we should use test-runner to test the repo itself :)

**Comment by bandersongit** [comment]
100%, Chalk and Rely (formerly test-runner) currently use it

**Comment by bandersongit** [comment]
Thanks @davesnx !!
