### ISSUE TITLE
Rely: Compiler error when running example

### ISSUE THREAD

**Issue by bryphe** [facebookexperimental/reason-native#38]
The `rely` docs suggest you should structure your tests like this: 
```
open TestFramework;
 
describe("my first test suite", ({test}) => {
  test("1 + 1 should equal 2", ({expect}) => {
    expect.int(1 + 1).toBe(2);
  });
});
```

However, this actually produces a warning (which is an error with default dune settings):
```
Error (warning 9): the following labels are not bound in this record pattern:
describe
Either bind these labels explicitly or add '; _' to the pattern.
```

The compiler wants this to be:
```diff
+    describe("my first test suite", ({describe, test}) => {
```
instead of:
```diff
-    describe("my first test suite", ({test}) => {
```

In my opinion - it feels a bit clunky to have to pass these values in (compared to the JS Jest API). It would be awesome if `describe`, `test`, and `expect` were all available from the `TestFramework` module.

Otherwise, it'd be worth updating the docs so that first-time users don't hit this error.

**Comment by kyldvs** [comment]
Interesting, I have not ever seen this warning and I don't think we ignore warning 9 anywhere explicitly. Not sure why this might be happening, we can investigate.

I actually prefer injecting `test` via the record to Jest's API. It makes the framework much cleaner to implement, fewer "magic" globals, and it avoids ordering issues. What should we do if you call describe within test or expect at the top level?

**Comment by bandersongit** [comment]
Warning 9 is ignored by default by ocamlc as far as I can tell. Per https://caml.inria.fr/pub/docs/manual-ocaml/comp.html, the default setting is `-w +a-4-6-7-9-27-29-32..42-44-45-48-50-60`

My guess is that the Dune dev profile is stricter than this by default and we have largely been developing with the release profile which is less strict.

**Comment by andreypopp** [comment]
Yes, dune's warnings are stricter than default `ocaml`'s ones.

I found Warning 9 very useful with records to make sure compiler catches cases where I need to handle all fields of the record (a common case with product types) when I'm adding a new field to a record. For cases where I don't need to handle all fields I just don't do destructuring then. Therefore I think the following API would work:
```
describe("my first test suite", define => {
  define.test("1 + 1 should equal 2", test => {
    test.expect.int(1 + 1).toBe(2);
  });
});
```

**Comment by kyldvs** [comment]
(copying my comment from elsewhere)

I don't like the change of having to be explicit with all fields in a record. I can understand the point of warning 9, and why it might be helpful in some cases, but this is explicitly not one of those cases. We don't really care about making sure each field in the record is listed and designed the API in that way on purpose.

Are there examples of this being an important thing that catches bugs? I can understand theoretically how it might come up, but it never seems relevant in practice.

I wonder what some alternatives might be.

**Comment by bryphe** [comment]
Hey, sorry for the slow reply here!

I should've put this originally, but here's an example branch where I have this problem.
https://github.com/bryphe/merlin-language-server/tree/bryphe/repro/reason-native-38

Note that I __do not explicitly set warning 9__. As @andreypopp mentioned, dune's default warnings are stricter. I _can_ workaround this by setting `(flags (:standard (-w -9)))` in the `dune` file.

I don't have a strong opinion about the warning, I just expected `rely` to build with this vanilla config. If we're OK with the behavior / API as is, suppressing this warning should be added to the `dune` config example. If it's desired for `rely` to work w/o changing the warning profile of `dune`, then @andreypopp 's suggestion sounds reasonable.

Regarding the global API:
>  It makes the framework much cleaner to implement
This makes sense, but IMO it should be the _very last_ consideration - the developer experience when using the library should be more important than what the framework has to do under the hood.

>  fewer "magic" globals
Can totally understand the rationale for this 😄 

>  and it avoids ordering issues. 
Hmm, what ordering issues? Is `jest` impacted by this too?

> What should we do if you call describe within test or expect at the top level?
I believe `jest` would have solved these problems - what does it do in these cases? Throwing an exception seems reasonable to me.

My personal preference would still be for the global API... but I understand where you're coming from too!

**Comment by kyldvs** [comment]
Yeah, we want this to work well "out of the box" without having to do custom setup in dune files. Perhaps our recommendation will be to do whichever of these the user prefers:

- Use `{field, _}` syntax for records
- Or ignore warning 9

It would be nice if we could use some sort of annotation on the record types to ignore warning 9 explicitly for everyone, since it is not relevant for these records.

---

(this is getting a little off-topic from original issue, if you want to keep discussing I'm happy to do so though, perhaps in another issue)

> very last consideration

Yeah, definitely far less important than the dev experience. I do think it is still an important consideration. If something can't be implemented cleanly and becomes full of hacks to satisfy a particular API it can cause the framework to be hard to maintain and hard to adapt. That indirectly affects the dev experience.

> what ordering issues

This is referring to the next sentence 😄 sorry I was not clear.

> Throwing an exception seems reasonable to me

It is a solution, but I think it's a much worse experience. We don't want to do exactly what Jest does if we can do better. We want to catch or prevent issues at compile time rather than defer them to runtime (just like with static type checking). In the current setup it is harder to call things out of order, you would have to intentionally break it by storing the provided functions in mutable state out of the current scope.

As we start expanding the capabilities of Rely, everything being a global will become a mess. These are some of the functions that we could add:

- https://jestjs.io/docs/en/api
- https://jestjs.io/docs/en/jest-object

**Comment by thangngoc89** [comment]
A little bikeshedding, I like that ava makes static type inferences easier

```
import test from 'ava';

test('foo', t => {
	t.pass();
});

test('bar', async t => {
	const bar = Promise.resolve('bar');
	t.is(await bar, 'bar');
});
```

**Comment by bandersongit** [comment]
The syntax that @thangngoc89 and @andreypopp is in fact available with the current API (mod the ava specific utilities). The below works out of the box with Rely.

```
open TestFramework;

describe("my test suite", d => {
  d.test("my test", t => {
    t.expect.int(1 + 1).toBe(2);
  });
});
```

How do people feel about updating the docs accordingly?

@bryphe @kyldvs 
I agree with not liking the magic globals and the assertion that UX should trump implementation details, Jest's behavior with improper nesting of describe/test isn't great if I recall correctly. In the past I have had issues with various CI reporters not liking tests that weren't inside describes.

**Comment by kyldvs** [comment]
I think we should continue to use destructuring syntax in the docs, and have the official recommendation to be ignoring warning 9. Then we can mention two alternatives, `{expect, _}` or `t.expect` syntaxes.

**Comment by bryphe** [comment]
Thanks all for your thoughts on this!

>  think we should continue to use destructuring syntax in the docs, and have the official recommendation to be ignoring warning 9. Then we can mention two alternatives, {expect, _} or t.expect syntaxes.

Sounds reasonable to me. There's already a prescribed `dune` config (ie, including the `-linkall` and `-g` flags), so not a big deal to suppress the warning there too.
