### ISSUE TITLE
Refmterr on Opam

### ISSUE THREAD

**Issue by osener** [facebookexperimental/reason-native#75]
I enjoy using refmterr in dune+opam projects, but it seems to get moved around a lot and I often have trouble figuring out how to install it and where to get it from. Is it possible to publish it on main opam repository?

**Comment by jordwalke** [comment]
It is not yet on opam and we just completed a large refactor that makes it be implemented on top of Pastel and file-context-printer so it would require releasing all of those packages to opam which is also a good idea but we need someone to volunteer with the releases.

**Comment by osener** [comment]
Thanks for the quick response! This is something I wanted to bring up for a while but couldn't because the previous Refmterr repository didn't accept issues, but I just noticed the **Status** message in reason-native README highlighting that it's planned for all packages. I'll close this issue.
